"""empty message

Revision ID: 799eddd26822
Revises: f5b916aae759
Create Date: 2020-08-13 13:52:26.849996

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799eddd26822'
down_revision = 'f5b916aae759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True, default=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_complete'), 'builds', ['complete'], unique=False)
    op.create_index(op.f('ix_builds_end_time'), 'builds', ['end_time'], unique=False)
    op.create_index(op.f('ix_builds_start_time'), 'builds', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builds_start_time'), table_name='builds')
    op.drop_index(op.f('ix_builds_end_time'), table_name='builds')
    op.drop_index(op.f('ix_builds_complete'), table_name='builds')
    op.drop_table('builds')
    # ### end Alembic commands ###
