"""empty message

Revision ID: 7d9f1fe19b3b
Revises: 799eddd26822
Create Date: 2020-08-25 12:28:08.241409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9f1fe19b3b'
down_revision = '799eddd26822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('builds', 'status')
    # ### end Alembic commands ###
