"""empty message

Revision ID: 8f9b5d037747
Revises: 
Create Date: 2020-08-03 18:21:59.056859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9b5d037747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'in_cgem', new_column_name='in_team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'in_team', new_column_name='in_cgem')
    # ### end Alembic commands ###
