"""empty message

Revision ID: b76d11c55ccb
Revises: 635fbd80a8a6
Create Date: 2021-05-24 15:52:44.628443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76d11c55ccb'
down_revision = '635fbd80a8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smarts',
    sa.Column('smarts_hash', sa.String(length=32), nullable=False),
    sa.Column('query_name', sa.Text(), nullable=False),
    sa.Column('smarts_str', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('smarts_hash'),
    sa.UniqueConstraint('query_name')
    )
    op.create_table('matches',
    sa.Column('smarts_hash', sa.String(length=32), nullable=False),
    sa.Column('inchi_key', sa.String(length=27), nullable=False),
    sa.Column('sub_match', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['smarts_hash'], ['smarts.smarts_hash'], ),
    sa.PrimaryKeyConstraint('smarts_hash', 'inchi_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('smarts')
    # ### end Alembic commands ###
